# Generated by Django 4.2.6 on 2023-11-20 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAutor', models.CharField(max_length=200)),
                ('apellidoAutor', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20)),
                ('telefonoAutor', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('idEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEditorial', models.CharField(max_length=200)),
                ('direccionEditorial', models.CharField(max_length=200)),
                ('ciudadEditorial', models.CharField(max_length=200)),
                ('numeroEditorial', models.CharField(max_length=40)),
                ('telefonoEditorial', models.CharField(max_length=40)),
                ('faxEditorial', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('tituloLibro', models.CharField(max_length=200)),
                ('generoLibro', models.CharField(max_length=200)),
                ('anoPublicacion', models.DateField()),
                ('idiomaLibro', models.CharField(max_length=40)),
                ('paginasLibro', models.CharField(max_length=40)),
                ('precioLibro', models.CharField(max_length=40)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesApp.editorial')),
            ],
        ),
    ]
