# Generated by Django 4.2.6 on 2023-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('FechaNacimiento', models.CharField(max_length=20)),
                ('Sexo', models.DateField(max_length=20)),
                ('Telefono', models.DateField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
            ],
        ),
    ]
