# Generated by Django 4.2.6 on 2023-11-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0002_rename_apellido_autor_apellidoautor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefonoAutor',
            field=models.CharField(max_length=10),
        ),
    ]
