# Generated by Django 4.2.6 on 2023-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0004_alter_autor_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fechaNacimiento',
            field=models.CharField(max_length=30),
        ),
    ]
